make: Makefile iithesis.cls iithesis.tex abstracts.tex bibitems.tex Chapters/*.tex Appendices/*.tex iithesis.pdf 
	pdflatex iithesis.tex

clean: Makefile
	rm -rf *.aux */*.aux *.log *.out *.toc *.fls *.fdb_latexmk *.synctex.gz
